from tkinter import*
import datetime
x = datetime.datetime.now() 
a=x.strftime("%x %A")
b=x.strftime("%I:%M %p")
c=x.strftime("%A")
d=x.strftime("%H:%M")
e=x.strftime("%C")
f=(e,"century")
root=Tk()
root.geometry("350x40")
root.minsize(350,40)
root.maxsize(350,40)
root.title("date and time ")
hel=Frame(root,borderwidth=6, bg="white",relief=SUNKEN)
hel.pack(anchor="nw")
# date
def date():
    me=Tk()
    me.geometry("360x50")
    me.minsize(360,50)
    me.maxsize(360,50)
    me.title("Date")
    melabel = Label(me,text=a,bg='White',font=("Times",30,'bold'))
    melabel.pack(side=TOP)
    me.mainloop()
# time
def time():
    me=Tk()
    me.geometry("170x50")
    me.minsize(170,50)
    me.maxsize(170,50)
    me.title("Time")
    melabel = Label(me,text=b,bg='White',font=("Times",30,'bold'))
    melabel.pack(side=TOP)
    me.mainloop()
# day
def day():
    me=Tk()
    me.geometry("200x50")
    me.minsize(200,50)
    me.maxsize(200,50)
    me.title("Day")
    melabel = Label(me,text=c,bg='White',font=("Times",30,'bold'))
    melabel.pack(side=TOP)
    me.mainloop()
# century
def century():
    me=Tk()
    me.geometry("200x50")
    me.minsize(200,50)
    me.maxsize(200,50)
    me.title("Century")
    melabel = Label(me,text=f,bg='White',font=("Times",30,'bold'))
    melabel.pack(side=TOP)
    me.mainloop()
# button 
b1=Button(hel,fg="black",text="Date",command=date)
b1.pack(padx=23,side=LEFT)
b2=Button(hel,fg="black",text="Time",command=time)
b2.pack(padx=23,side=LEFT)
b3=Button(hel,fg="black",text="Day",command=day)
b3.pack(padx=23,side=LEFT)
b4=Button(hel,fg="black",text="Century",command=century)
b4.pack(padx=23,side=LEFT)
root.mainloop()
