from tkinter import *
from tkinter import messagebox
root=Tk()
def hel():
    print("Male")
def heli():
    print("Female")
def abcd():
    root=Tk()
    root.geometry("400x280")
    Label(root, text="Here is Your Data", font="comicsansms 13 bold", pady=15).grid(row=0, column=3)
    name = Label(root, text="Name")
    phone = Label(root, text="Phone")
    gender = Label(root, text="Gender")
    address = Label(root, text="Address")
    age = Label(root, text="Age")
    name.grid(row=1, column=2)
    phone.grid(row=2, column=2)
    gender.grid(row=3, column=2)
    address.grid(row=4, column=2)
    age.grid(row=5, column=2)
    a=  (((namevalue.get()).capitalize()))
    b=  (((phonevalue.get()).capitalize()))
    c=  (((gendervalue.get()).capitalize()))
    d=  (((addressvalue.get()).capitalize())) 
    e= (((agevalue.get()).capitalize()))   
    name = Label(root, text=a)
    phone = Label(root, text=b)
    gender = Label(root, text=c)
    address = Label(root, text=d)
    age = Label(root, text=e)
    name.grid(row=1, column=3)
    phone.grid(row=2, column=3)
    gender.grid(row=3, column=3)
    address.grid(row=4, column=3)
    age.grid(row=5, column=3)
    root.mainloop()
def saveas():
    a=((namevalue.get()).capitalize())
    b=((phonevalue.get()).capitalize())
    c=((gendervalue.get()).capitalize())
    d=((addressvalue.get()).capitalize())
    e=((agevalue.get()).capitalize())
    f=open('now.txt','w')
    f.write("User Name Is :-   ")
    f.write("\n")
    f.write(a)
    f.write("\n")  
    f.write("User Phone Number Is :-   ")
    f.write("\n")
    f.write(b)
    f.write("\n")
    f.write("User Gender Is:-   ")
    f.write("\n")
    f.write(c)
    f.write("\n")
    f.write("User Address Is:-   ")
    f.write("\n")
    f.write(d)
    f.write("\n")
    f.write("User Age Is:-   ")
    f.write("\n")
    f.write(e)
    f.close()
def ge():
    if(gendervalue.get()).capitalize()=="Male":
        print("ok")
        
    elif (gendervalue.get()).capitalize()== "Female":
        print("ok")
        
    else:
        me=Tk()
        me.geometry("1000x50")
        me.title("please")
        melabel=Label(me,text="sorry please enter male or female",font=("Times",30,'bold'))
        melabel.pack()
def ages():
    verma=int(agevalue.get())
    if verma <=100:
        print("ok")
    if verma>100 :
        me=Tk()
        me.geometry("1000x50")
        me.title("please")
        melabel=Label(me,text="sorry please enter your correct age",font=("Times",30,'bold'))
        melabel.pack()
def ph():
    happy=int(phonevalue.get())
    if happy>1000000000:
        print("ok phonenumber")
    if happy>10000000000:
        me=Tk()
        me.geometry("1000x50")
        me.title("please")
        melabel=Label(me,text="sorry please enter correct phone number",font=("Times",30,'bold'))
        melabel.pack()

root.geometry("644x344")
foodservicevalue2 = IntVar()
Label (root,text="welcome buddy",font="comicsansms 13 bold",pady=15).grid(row=0,column=3)
Label(root,text="name").grid(row=1, column=2)
Label(root, text="Phone").grid(row=2, column=2)
Label(root, text="Gender").grid(row=3, column=2)
Label(root, text="Address").grid(row=4, column=2)
Label(root, text="Age").grid(row=5, column=2)
namevalue = StringVar()
phonevalue = StringVar()
gendervalue = StringVar()
addressvalue = StringVar()
agevalue = StringVar()
Entry(root, textvariable=namevalue).grid(row=1, column=3)
Entry(root, textvariable=phonevalue).grid(row=2, column=3)
Entry(root, textvariable=gendervalue).grid(row=3, column=3)
Entry(root, textvariable=addressvalue).grid(row=4, column=3)
Entry(root, textvariable=agevalue).grid(row=5, column=3)
def save():
    ph()
    ge()
    ages()
    abcd()
def hello():
    messagebox.showinfo("Note","your data is saved secure")
    me=Tk()
    me.geometry("1000x50")
    me.title("Want to book")
    melabel=Label(me,text="Your extra fast servies is booked",font=("Times",30,'bold'))
    melabel.pack()
    f=open("now.txt",'a')
    f.write( "\n")
    f.write("want to book a extra")
    f.close()
Button(text="sumit",command=save).grid(row=7,column=3)
Button(text=" save ",command=saveas).grid(row=9,column=3)
kite=Checkbutton(text="want to keep secure",variable=foodservicevalue2,command=hello)
kite.grid(row=11,column=3)

root.mainloop()